name: Build BE3600
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        run: sudo apt update && sudo apt install -y build-essential libncurses-dev gawk flex bison git python3 unzip libssl-dev libelf-dev

      - name: Clone SDK
        run: git clone --depth 1 https://github.com/gl-inet/sdk.git openwrt

      - name: Download files
        run: cd openwrt && ./download.sh ipq53xx

      - name: Add turboacc source
        run: |
          cd openwrt
          echo "src-git turboacc https://github.com/chenmozhijin/turboacc.git;luci" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Config
        run: |
          cd openwrt
          echo CONFIG_TARGET_ipq53xx=y >> .config
          echo CONFIG_TARGET_ipq53xx_ipq5312=y >> .config
          echo CONFIG_TARGET_PROFILE_glinet_gl_be3600=y >> .config
          echo CONFIG_PACKAGE_luci-app-turboacc=y >> .config
          echo CONFIG_PACKAGE_kmod-shortcut-fe=n >> .config
          make defconfig

      - name: Compile
        run: cd openwrt && make -j$(nproc)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: BE3600-TurboACC-Firmware
          path: openwrt/bin/targets/ipq53xx/ipq5312/*.bin
